
name: Run tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
      
  workflow_dispatch:
    inputs:
      appName:
        default: CT-WEB workflow
        required: true
        description: Project name
      arguments:
        required: false
        description: Additional gradle arguments
        default: ""
      
jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
     # - name: Start Selenoid Server
      #  uses: Xotabu4/selenoid-github-action@v2

      - name: Checkout
        uses: actions/checkout@v2
 
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run tests in Gradle
        run: ./gradlew clean test -Dselenide.headless=true --info --rerun-tasks
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-report
          path: build/reports/
