name: CT-WEB workflow

on:
  schedule:
    - cron: '0 20 * * *' # every 20:00 UTC (23:00 MSK)

  workflow_dispatch:
    inputs:
      appName:
        default: CT-WEB workflow
        required: true
        description: Project name
      arguments:
        required: false
        description: Additional gradle arguments
        default: ""

jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run tests in Gradle
        run: ./gradlew clean test -Dselenide.headless=true --info --rerun-tasks
      - name: Run tests in Maven
        run: ./mvnw clean test -Dselenide.headless=true
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: build/reports/
